Kill all old jobs

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -94,12 +94,17 @@ cleanup-jobs:
   stage: .pre
   needs: []
   script:
-       - ps -u $(whoami) -o pid,comm,command,cputime,vsize,uname,pcpu,pmem
+       - OUTPUT_FORMAT=pid,comm,cputime,vsize,uname,pcpu,pmem,tty
+       - ps -u $(whoami) -o ${OUTPUT_FORMAT}
        - |
-         for pid in $(ps -u $(whoami) -o pid,cmd,tty | awk '/\<mbdyn\>|\<octave\>/{if ($3 == "?") {print $1};}'); do
-           kill -9 "${pid}"
+         for pid in $(ps -u $(whoami) -o pid,comm,tty | awk '/mbdyn|octave/{if ($3 == "?") {print $1};}'); do
+           echo "Process ${pid} will be killed"
+           ps -p ${pid} -o ${OUTPUT_FORMAT}
+           if ! kill -9 ${pid}; then
+               echo "Failed to kill ${pid}"
+           fi
          done
-       - ps -u $(whoami) -o pid,comm,command,cputime,vsize,uname,pcpu,pmem
+       - ps -u $(whoami) -o ${OUTPUT_FORMAT}
   
 mkl-build-job:       # This job runs in the build stage, which runs first.
   stage: build
