Install missing binary fem_pre_mesh_size; merge branch fix-netcdf-eig

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -18,6 +18,9 @@
 
 variables:
   MBD_INSTALL_PREFIX: "/home/gitlab-runner/local/mbdyn-test-install/" ## Local installation directory for MBDyn
+  MBD_MERGE_BRANCH: "fix-netcdf-eig"
+  GMSH_INSTALL_PREFIX: "/home/gitlab-runner/local/gmsh-test-install/" ## Local installation directory for Gmsh
+  MBOCT_INSTALL_PREFIX: "/home/gitlab-runner/local/mboct-test-install/" ## Local installation directory for Gmsh
   NC_INSTALL_PREFIX: "/home/gitlab-runner/local/netcdf-test-install/" ## Local installation directory for NetCDF
   NL_INSTALL_PREFIX: "/home/gitlab-runner/local/nlopt-test-install/" ## Local installation directory for nlopt
   MBD_BUILD_DIR: "/home/gitlab-runner/install/mbdyn-test-build/" ## Local build directory
@@ -97,11 +100,6 @@ nlopt-build-job:       # This job runs in the build stage, which runs first.
 mbdyn-build-job:       # This job runs in the build stage, which runs first.
   stage: build
   script:
-    #- echo "Check cpuinfo ..."
-    #- cat /proc/cpuinfo
-    #- echo "Check the host system ..."
-    #- uname -a
-    #- find ${HOME} -name config.status -execdir make distclean ';'
     #- echo "Cleanup some garbage ..."
     #- |
     #  for dirent in autom4te.cache build contrib CVS etc include libraries manual mbdyn modules packaging tests utils var; do
@@ -110,12 +108,21 @@ mbdyn-build-job:       # This job runs in the build stage, which runs first.
           #rm -rf ${HOME}/${dirent}
       #  fi
     #  done
-    #- echo "Check the contents of the home directory ..."
-    #- find ${HOME} -type f # Let us check if we left some garbage there ...
     - printf "checkout branch \"%s\"\n" "$CI_COMMIT_BRANCH"
     - git checkout $CI_COMMIT_BRANCH --force
     - printf "pulling\n"
     - git pull --force
+    - |
+      if ! test -z "${MBD_MERGE_BRANCH}" && ! test -z "`git branch --list | grep ${MBD_MERGE_BRANCH}`"; then
+        if git fetch origin "${MBD_MERGE_BRANCH}":"${MBD_MERGE_BRANCH}"; then
+          if git merge --no-commit "${MBD_MERGE_BRANCH}"; then
+            echo "branch ${MBD_MERGE_BRANCH} was merged"
+          else
+            echo "branch ${MBD_MERGE_BRANCH} could not be merged"
+            git merge --abort
+          fi
+        fi
+      fi
     ## Let's try to speed up the build process a bit
     ## Execute bootstrap.sh and configure only if needed
     ## This conditional execution may be removed as soon as the testsuite is finished
@@ -179,11 +186,6 @@ mbdyn-build-job:       # This job runs in the build stage, which runs first.
         fi
       fi
       test -f Makefile
-    # - echo "Determine the number of build jobs ..."
-    # - |
-    #   if test -f /proc/cpuinfo ; then
-    #     MBD_NUM_BUILD_JOBS=`awk 'BEGIN{max=1;}/^processor\>/{if ($3 + 1 >= max) max = $3 + 1; } END{ print max }' /proc/cpuinfo`;
-    #   fi
     - printf "Compiling the code using %s jobs ...\n" ${MBD_NUM_BUILD_JOBS}
     - make -j${MBD_NUM_BUILD_JOBS}
     - echo "Clean up local installation directory"
@@ -252,6 +254,19 @@ octave-pkg-build-job:       # This job runs in the build stage, which runs first
                       if ! make CXXFLAGS="${MBD_COMPILER_FLAGS}" -C "${pkgname}" install_local; then
                           printf "failed to build package \"%s\"\n" "${pkgname}"
                       fi
+                      case "${pkgname}" in
+                      mboct-fem-pkg)
+                          ## FIXME: Need install fem_pre_mesh_size since octave's package manager does not run "make install"
+                          mkdir -p "${MBOCT_INSTALL_PREFIX}/bin"
+                          pushd "${pkgname}/src"
+                          chmod u+x bootstrap
+                          ./bootstrap
+                          ./configure CXXFLAGS="${MBD_COMPILER_FLAGS}" --prefix="${MBOCT_INSTALL_PREFIX}"
+                          make
+                          make install
+                          popd
+                          ;;
+                      esac
                       ;;
                   *)
                       # Assume that the package is hosted at octave-forge
@@ -275,21 +290,22 @@ gmsh-build-job:       # This job runs in the build stage, which runs first.
    script:
        - echo "gmsh build"
        - |
-         export PATH=${MBD_INSTALL_PREFIX}/bin:${PATH}
+         export PATH=${GMSH_INSTALL_PREFIX}/bin:${PATH}
          if gmsh --version >& /dev/null && test ${MBD_GMSH_REINSTALL} = "no" -a ${MBD_CLEAN_ALL} = "no" ; then
            echo "Gmsh was already installed ..."
            exit 0
          fi
        - wget http://www.gmsh.info/bin/Linux/gmsh-stable-Linux64.tgz
        - tar -zxvf gmsh-stable-Linux64.tgz
-       - install gmsh-*.*.*-Linux64/bin/gmsh ${MBD_INSTALL_PREFIX}/bin
-       - ${MBD_INSTALL_PREFIX}/bin/gmsh --version
+       - mkdir -p "${GMSH_INSTALL_PREFIX}/bin"
+       - install gmsh-*.*.*-Linux64/bin/gmsh "${GMSH_INSTALL_PREFIX}/bin"
+       - "${GMSH_INSTALL_PREFIX}/bin/gmsh" --version
 
 octave-pkg-test-job:   # This job runs in the test stage.
   stage: test    # It only starts when the job in the build stage completes successfully.
   script:
       - echo "octave packages test job"
-      - export PATH=${MBD_INSTALL_PREFIX}/bin:${PATH}
+      - export PATH=${MBD_INSTALL_PREFIX}/bin:${GMSH_INSTALL_PREFIX}/bin:${MBOCT_INSTALL_PREFIX}/bin:${PATH}
       - export AWKPATH=${MBD_INSTALL_PREFIX}/share/awk:${AWKPATH}
       - which mbdyn
       - mbdyn --version
