Fix list of modules

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -275,6 +275,9 @@ mbdyn-build-job:       # This job runs in the build stage, which runs first.
         else
             echo "Warning: MKL_PKG_CONFIG_PATH could not be detected"
         fi
+    ## FIXME: We cannot use "${MBD_WITH_MODULE}" or "$MBD_WITH_MODULE" because this will prevent substitution of variables.
+    ## FIXME: On the other hand --with-module=$MBD_WITH_MODULE would be invalid as well.
+    - mbd_with_module=$MBD_WITH_MODULE
     - printf "configure ...\n"
     - |
       if ! test -f Makefile; then
@@ -296,7 +299,7 @@ mbdyn-build-job:       # This job runs in the build stage, which runs first.
                     ${PARDISO_FLAGS} \
                     --with-suitesparseqr \
                     --with-static-modules \
-                    --with-module="${MBD_WITH_MODULE}" \
+                    --with-module="${mbd_with_module}" \
                     --disable-Werror \
                     --with-trilinos ; then
                     ## FIXME: We should not use --disable-Werror, but need to fix a few warnings caused by Octave's headers instead
@@ -480,6 +483,29 @@ gmsh-build-job:       # This job runs in the build stage, which runs first.
        - rm -rf gmsh-*.*.*-Linux64
        - ${GMSH_INSTALL_PREFIX}/bin/gmsh --version
 
+mbdyn-modules-test-job:   # This job runs in the test stage.
+  stage: test    # It only starts when the job in the build stage completes successfully.
+  needs:
+    - job: octave-pkg-build-job ## module-triangular_contact is using Octave
+    - job: gmsh-build-job ## module-triangular_contact is using Gmsh
+    - job: mbdyn-build-job
+  script:
+      - echo "MBDyn modules test job"
+      - export PATH=${MBD_INSTALL_PREFIX}/bin:${GMSH_INSTALL_PREFIX}/bin:${MBOCT_INSTALL_PREFIX}/bin:${PATH}
+      - export AWKPATH=${MBD_INSTALL_PREFIX}/share/awk:${AWKPATH}
+      - MBD_MODULE_TEST_INPUT_DIR="`pwd`/modules"
+      - test -d "${MBD_MODULE_TEST_INPUT_DIR}"
+      - chmod +x testsuite/simple_testsuite.sh
+      - |
+        ## FIXME: It seems that everything must be on one long line ...
+        if testsuite/simple_testsuite.sh --timeout "${MBD_MODULE_TEST_TIMEOUT}" --prefix-output "${MBD_MODULE_TEST_OUTPUT_DIR}" --prefix-input "${MBD_MODULE_TEST_INPUT_DIR}"; then
+          echo "MBDyn modules test job passed"
+        else
+          echo "MBDyn modules test job failed - exit status will not be checked yet"
+          ## FIXME: Enable the next line as soon as all tests pass
+          ## exit 1
+        fi
+
 octave-pkg-test-job:   # This job runs in the test stage.
   stage: test    # It only starts when the job in the build stage completes successfully.
   needs:
@@ -508,28 +534,6 @@ octave-pkg-test-job:   # This job runs in the test stage.
       ## FIXME: It seems that everything must be on one long line
       - testsuite/octave_pkg_testsuite.sh --octave-pkg-list "${OCT_PKG_LIST}" --octave-exec "${OCTAVE_EXEC}" --octave-pkg-tests "${OCT_PKG_TESTS}" --timeout "${OCT_PKG_TIMEOUT}" --octave-pkg-test-dir "${OCT_PKG_TEST_OUTPUT_DIR}"
 
-mbdyn-modules-test-job:   # This job runs in the test stage.
-  stage: test    # It only starts when the job in the build stage completes successfully.
-  needs:
-    - job: octave-pkg-build-job ## module-triangular_contact is using Octave
-    - job: gmsh-build-job ## module-triangular_contact is using Gmsh
-    - job: mbdyn-build-job
-  script:
-      - echo "MBDyn modules test job"
-      - export PATH=${MBD_INSTALL_PREFIX}/bin:${GMSH_INSTALL_PREFIX}/bin:${MBOCT_INSTALL_PREFIX}/bin:${PATH}
-      - export AWKPATH=${MBD_INSTALL_PREFIX}/share/awk:${AWKPATH}
-      - MBD_MODULE_TEST_INPUT_DIR="`pwd`/modules"
-      - test -d "${MBD_MODULE_TEST_INPUT_DIR}"
-      - chmod +x testsuite/simple_testsuite.sh
-      - |
-        ## FIXME: It seems that everything must be on one long line ...
-        if testsuite/simple_testsuite.sh --timeout "${MBD_MODULE_TEST_TIMEOUT}" --prefix-output "${MBD_MODULE_TEST_OUTPUT_DIR}" --prefix-input "${MBD_MODULE_TEST_INPUT_DIR}"; then
-          echo "MBDyn modules test job passed"
-        else
-          echo "MBDyn modules test job failed - exit status will not be checked yet"
-          ## FIXME: Enable the next line as soon as all tests pass
-          ## exit 1
-        fi
 
 deploy-job:      # This job runs in the deploy stage.
   stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
