Clone private tests ...

diff --git a/testsuite/mbdyn-cleanup-job.yml b/testsuite/mbdyn-cleanup-job.yml
--- a/testsuite/mbdyn-cleanup-job.yml
+++ b/testsuite/mbdyn-cleanup-job.yml
@@ -6,6 +6,15 @@ mbdyn-bootloader-job:
             echo ${MBD_TESTSUITE_BOOTLOADER}
             ${MBD_TESTSUITE_BOOTLOADER}
           fi
+        - MBD_TESTS_PUBLIC_INPUT_DIR=${CI_PROJECT_DIR}/${MBD_TESTS_PUBLIC_INPUT_DIR}
+        - printf "host=gitlab.com\nprotocol=https\nusername=mbdyn.user1\npassword=glpat-fjtcsh4jPhNmyAsnLCzb\n" | git credential fill
+        - |
+          if ! test -d ${MBD_TESTS_PUBLIC_INPUT_DIR}; then
+            if ! git clone ${MBD_TESTS_PUBLIC_GITLAB} ${MBD_TESTS_PUBLIC_INPUT_DIR}; then
+              echo "Failed to clone ${MBD_TESTS_PUBLIC_GITLAB}"
+              exit 1
+            fi
+          fi
 
 mbdyn-cleanup-job:
   stage: .pre
