Testsuite gcov

diff --git a/testsuite/mbdyn-tests-private-test-job.yml b/testsuite/mbdyn-tests-private-test-job.yml
--- a/testsuite/mbdyn-tests-private-test-job.yml
+++ b/testsuite/mbdyn-tests-private-test-job.yml
@@ -34,25 +34,33 @@
 # for use in the software MBDyn as described
 # in the GNU Public License version 2.1
 
+variables:
+  ## Error codes which should not cause the pipeline to fail:
+  ## - timeout                    (0x2)
+  ## - module not found           (0x4)
+  ## - suppressed errors          (0x8)
+  ## - test failed with status 1  (0x10)
+  MBD_TESTS_PRIVATE_EXIT_STATUS_MASK: "0x0A" ## FIXME: We need to check how many failed tests we have, and which tests actually failed.
+  ## Timeout per model (by default in minutes, "s" for seconds, "m" for minutes "h" for hours)
+  ## Timeout value should not be "unlimited" if we are testing models which are using sockets, because this might block our pipeline forever!
+  ## Actually the overall timeout of 12 hours per job must be considered.
+  MBD_TESTS_PRIVATE_TIMEOUT: "10s"
+  ## FIXME: It seems that MBDyn's EDGE interface does not respond to SIGTERM.
+  ## FIXME: Until this issues is fixed, all those tests must be disabled!
+  ## FIXME: This is achieved by setting MBD_TESTS_PRIVATE_FILTER_EXPR in order to exclude all the models in "forces/modalext" and "forces/strext".
+  ## See https://public.gitlab.polimi.it/DAER/mbdyn/-/settings/ci_cd
+  MBD_TESTS_PRIVATE_NUM_TASKS: 12
+  MBD_TESTS_PRIVATE_LOG_FILE: "mbdyn-tests-private-test-job.log"
+  MBD_TESTS_PRIVATE_STATUS_FILE: "mbdyn-tests-private-test-job.status"
+  ## Patched test settings:
+  ## Warning: Do not add too many options here because the total number of tests to be executed may increase dramatically just by adding a few options!
+  MBD_TESTS_PRIVATE_LINEAR_SOLVERS: "umfpack"
+  MBD_TESTS_PRIVATE_MATRIX_HANDLERS: "map cc grad"
+  MBD_TESTS_PRIVATE_SCALE_METHODS: "rowmaxcolumnmax"
+  MBD_TESTS_PRIVATE_SCALE_WHEN: "always"
+  MBD_TESTS_PRIVATE_NONLINEAR_SOLVERS: "newtonraphson linesearch nox"
+  MBD_TESTS_PRIVATE_METHODS: "impliciteuler ms2,0."
 mbdyn-tests-private-test-job:   # This job runs in the test stage.
-  variables:
-     ## Error codes which should not cause the pipeline to fail:
-     ## - timeout                    (0x2)
-     ## - module not found           (0x4)
-     ## - suppressed errors          (0x8)
-     ## - test failed with status 1  (0x10)
-     MBD_TESTS_PRIVATE_EXIT_STATUS_MASK: "0x0A" ## FIXME: We need to check how many failed tests we have, and which tests actually failed.
-     ## Timeout per model (by default in minutes, "s" for seconds, "m" for minutes "h" for hours)
-     ## Timeout value should not be "unlimited" if we are testing models which are using sockets, because this might block our pipeline forever!
-     ## Actually the overall timeout of 12 hours per job must be considered.
-     MBD_TESTS_PRIVATE_TIMEOUT: "10s"
-     ## FIXME: It seems that MBDyn's EDGE interface does not respond to SIGTERM.
-     ## FIXME: Until this issues is fixed, all those tests must be disabled!
-     ## FIXME: This is achieved by setting MBD_TESTS_PRIVATE_FILTER_EXPR in order to exclude all the models in "forces/modalext" and "forces/strext".
-     ## See https://public.gitlab.polimi.it/DAER/mbdyn/-/settings/ci_cd
-     MBD_TESTS_PRIVATE_NUM_TASKS: 12
-     MBD_TESTS_PRIVATE_LOG_FILE: "mbdyn-tests-private-test-job.log"
-     MBD_TESTS_PRIVATE_STATUS_FILE: "mbdyn-tests-private-test-job.status"
   stage: test    # It only starts when the job in the build stage completes successfully.
   needs:
      - job: mkl-build-job
@@ -99,9 +107,9 @@ mbdyn-tests-private-test-job:   # This job runs in the test stage.
       - test_status="failed"
       - (testsuite/simple_testsuite.sh --suppressed-errors "${MBD_TESTS_PRIVATE_SUPPRESSED_ERRORS}" --regex-filter "${MBD_TESTS_PRIVATE_FILTER_EXPR}" --exit-status-mask "${MBD_TESTS_PRIVATE_EXIT_STATUS_MASK}" --timeout "${MBD_TESTS_PRIVATE_TIMEOUT}" --prefix-output "${MBD_TESTS_PRIVATE_OUTPUT_DIR}" --prefix-input "${MBD_TESTS_PRIVATE_INPUT_DIR}" --tasks "${MBD_TESTS_PRIVATE_NUM_TASKS}" ${MBD_SIMPLE_TESTSUITE_FLAGS} 2>&1 | tee -a "${log_file}") && test_status="passed"
       - echo "${test_status}" > "${status_file}"
-      - echo "-------------- PATCHED TESTS --------------------" | tee -a "${log_file}"      
+      - echo "-------------- PATCHED TESTS --------------------" | tee -a "${log_file}"
       - test_status="failed"
-      - (testsuite/simple_testsuite_patched.sh --linear-solvers "umfpack" --matrix-handlers "map cc grad" --scale-methods "rowmaxcolumnmax" --scale-when "never always" --nonlinear-solvers "newtonraphson linesearch nox" --method "impliciteuler ms2,0." --suppressed-errors "${MBD_TESTS_PRIVATE_SUPPRESSED_ERRORS}" --regex-filter "${MBD_TESTS_PRIVATE_FILTER_EXPR}" --exit-status-mask "${MBD_TESTS_PRIVATE_EXIT_STATUS_MASK}" --timeout "${MBD_TESTS_PRIVATE_TIMEOUT}" --prefix-output "${MBD_TESTS_PRIVATE_OUTPUT_DIR}" --prefix-input "${MBD_TESTS_PRIVATE_INPUT_DIR}" --tasks "${MBD_TESTS_PRIVATE_NUM_TASKS}" ${MBD_SIMPLE_TESTSUITE_FLAGS} --exclude-inverse-dynamics 1 2>&1 | tee -a "${log_file}") && test_status="passed"
+      - (testsuite/simple_testsuite_patched.sh --linear-solvers "${MBD_TESTS_PRIVATE_LINEAR_SOLVERS}" --matrix-handlers "${MBD_TESTS_PRIVATE_MATRIX_HANDLERS}" --scale-methods "${MBD_TESTS_PRIVATE_SCALE_METHODS}" --scale-when "${MBD_TESTS_PRIVATE_SCALE_WHEN}" --nonlinear-solvers "${MBD_TESTS_PRIVATE_NONLINEAR_SOLVERS}" --method "${MBD_TESTS_PRIVATE_METHODS}" --suppressed-errors "${MBD_TESTS_PRIVATE_SUPPRESSED_ERRORS}" --regex-filter "${MBD_TESTS_PRIVATE_FILTER_EXPR}" --exit-status-mask "${MBD_TESTS_PRIVATE_EXIT_STATUS_MASK}" --timeout "${MBD_TESTS_PRIVATE_TIMEOUT}" --prefix-output "${MBD_TESTS_PRIVATE_OUTPUT_DIR}" --prefix-input "${MBD_TESTS_PRIVATE_INPUT_DIR}" --tasks "${MBD_TESTS_PRIVATE_NUM_TASKS}" ${MBD_SIMPLE_TESTSUITE_FLAGS} --exclude-inverse-dynamics 1 2>&1 | tee -a "${log_file}") && test_status="passed"
       - echo "${test_status}" >> "${status_file}"
   artifacts:
     name: mbdyn-tests-private-test-job
@@ -109,3 +117,61 @@ mbdyn-tests-private-test-job:   # This job runs in the test stage.
     paths:
       - $MBD_TESTS_PRIVATE_OUTPUT_DIR/$MBD_TESTS_PRIVATE_LOG_FILE
       - $MBD_TESTS_PRIVATE_OUTPUT_DIR/$MBD_TESTS_PRIVATE_STATUS_FILE
+
+mbdyn-tests-private-test-job-gcov:   # This job runs in the test stage.
+  stage: test    # It only starts when the job in the build stage completes successfully.
+  needs:
+     - job: mkl-build-job
+       artifacts: true
+     - job: netcdf-c-build-job
+       artifacts: true
+     - job: netcdf-cxx4-build-job
+       artifacts: true
+     - job: mbdyn-build-job-gcov
+       artifacts: true
+     - job: mbdyn-tests-public-test-job-gcov ## Need to fetch all *.gcda and *.gcno files
+       artifacts: true
+  script:
+      - MBD_INSTALL_PREFIX=${CI_PROJECT_DIR}/${MBD_INSTALL_PREFIX_GCOV}
+      - OCT_PKG_INSTALL_PREFIX=${CI_PROJECT_DIR}/${OCT_PKG_INSTALL_PREFIX_GCOV}
+      - GMSH_INSTALL_PREFIX=${CI_PROJECT_DIR}/${GMSH_INSTALL_PREFIX}
+      - MBD_TESTS_PRIVATE_OUTPUT_DIR=${CI_PROJECT_DIR}/${MBD_TESTS_PRIVATE_OUTPUT_DIR_GCOV}
+      - MBD_TESTS_PRIVATE_INPUT_DIR=${CI_PROJECT_DIR}/${MBD_TESTS_PRIVATE_INPUT_DIR}
+      - echo "mbdyn-tests-private test job"
+      - export PATH=${MBD_INSTALL_PREFIX}/bin:${GMSH_INSTALL_PREFIX}/bin:${OCT_PKG_INSTALL_PREFIX}/bin:${PATH}
+      - export AWKPATH=${MBD_INSTALL_PREFIX}/share/awk:${AWKPATH}
+      - mkdir -p "${MBD_TESTS_PRIVATE_OUTPUT_DIR}" ## needed for realpath
+      - log_file="${MBD_TESTS_PRIVATE_OUTPUT_DIR}/${MBD_TESTS_PRIVATE_LOG_FILE}"
+      - status_file="${MBD_TESTS_PRIVATE_OUTPUT_DIR}/${MBD_TESTS_PRIVATE_STATUS_FILE}"
+      - echo "unexpected" > "${status_file}"
+      - |
+        if test -z "${MBD_TESTS_PRIVATE_GITLAB}"; then
+          echo "Because MBD_TESTS_PRIVATE_GITLAB was not defined in gitlab, no tests will be executed!" | tee "${log_file}"
+          exit 0
+        fi
+      - |
+        if ! test -d ${MBD_TESTS_PRIVATE_INPUT_DIR}; then
+          if ! git clone -b ${MBD_TESTS_PRIVATE_GITLAB_BRANCH} ${MBD_TESTS_PRIVATE_GITLAB} ${MBD_TESTS_PRIVATE_INPUT_DIR}; then
+            echo "${MBD_TESTS_PRIVATE_GITLAB} is not accessible" | tee -a "${log_file}"
+            exit 1
+          fi
+        fi
+      - test -d ${MBD_TESTS_PRIVATE_INPUT_DIR}
+      - curr_dir=`pwd`
+      - cd ${MBD_TESTS_PRIVATE_INPUT_DIR}
+      - git pull --force
+      - cd ${curr_dir}
+      - chmod +x testsuite/simple_testsuite.sh
+      ## FIXME: drives/string/distance will fail with status 139 if we are passing --pedantic --pedantic --pedantic
+      - echo "-------------- PATCHED TESTS --------------------" | tee -a "${log_file}"
+      - test_status="failed"
+      - (testsuite/simple_testsuite_patched.sh --linear-solvers "${MBD_TESTS_PRIVATE_LINEAR_SOLVERS}" --matrix-handlers "${MBD_TESTS_PRIVATE_MATRIX_HANDLERS}" --scale-methods "${MBD_TESTS_PRIVATE_SCALE_METHODS}" --scale-when "${MBD_TESTS_PRIVATE_SCALE_WHEN}" --nonlinear-solvers "${MBD_TESTS_PRIVATE_NONLINEAR_SOLVERS}" --method "${MBD_TESTS_PRIVATE_METHODS}" --suppressed-errors "${MBD_TESTS_PRIVATE_SUPPRESSED_ERRORS}" --regex-filter "${MBD_TESTS_PRIVATE_FILTER_EXPR}" --exit-status-mask "${MBD_TESTS_PRIVATE_EXIT_STATUS_MASK}" --timeout "${MBD_TESTS_PRIVATE_TIMEOUT}" --prefix-output "${MBD_TESTS_PRIVATE_OUTPUT_DIR}" --prefix-input "${MBD_TESTS_PRIVATE_INPUT_DIR}" --tasks "${MBD_TESTS_PRIVATE_NUM_TASKS}" ${MBD_SIMPLE_TESTSUITE_FLAGS} --exclude-inverse-dynamics 1 2>&1 | tee -a "${log_file}") && test_status="passed"
+      - echo "${test_status}" > "${status_file}"
+  artifacts:
+    name: mbdyn-tests-private-test-job-gcov
+    expire_in: 2 days
+    paths:
+      - $MBD_TESTS_PRIVATE_OUTPUT_DIR_GCOV/$MBD_TESTS_PRIVATE_LOG_FILE
+      - $MBD_TESTS_PRIVATE_OUTPUT_DIR_GCOV/$MBD_TESTS_PRIVATE_STATUS_FILE
+      - $MBD_TESTS_PRIVATE_OUTPUT_DIR_GCOV/**/*.stdout
+      - $MBD_BUILD_DIR_GCOV
diff --git a/testsuite/mbdyn-tests-public-test-job.yml b/testsuite/mbdyn-tests-public-test-job.yml
--- a/testsuite/mbdyn-tests-public-test-job.yml
+++ b/testsuite/mbdyn-tests-public-test-job.yml
@@ -34,17 +34,19 @@
 # for use in the software MBDyn as described
 # in the GNU Public License version 2.1
 
+variables:
+  ## Error codes which should not cause the pipeline to fail:
+  ## - timeout                    (0x2)
+  ## - module not found           (0x4)
+  ## - suppressed errors          (0x8)
+  MBD_TESTS_PUBLIC_EXIT_STATUS_MASK: "0x0"
+  ## Timeout per model (by default in minutes, "s" for seconds, "m" for minutes "h" for hours)
+  ## Timeout value should not be "unlimited" if we are testing models which are using sockets, because this might block our pipeline forever!
+  MBD_TESTS_PUBLIC_TIMEOUT: "unlimited"
+  MBD_TESTS_PUBLIC_NUM_TASKS: 12
+
 mbdyn-tests-public-test-job:   # This job runs in the test stage.
   variables:
-    ## Error codes which should not cause the pipeline to fail:
-    ## - timeout                    (0x2)
-    ## - module not found           (0x4)
-    ## - suppressed errors          (0x8)
-    MBD_TESTS_PUBLIC_EXIT_STATUS_MASK: "0x0"
-    ## Timeout per model (by default in minutes, "s" for seconds, "m" for minutes "h" for hours)
-    ## Timeout value should not be "unlimited" if we are testing models which are using sockets, because this might block our pipeline forever!
-    MBD_TESTS_PUBLIC_TIMEOUT: "unlimited"
-    MBD_TESTS_PUBLIC_NUM_TASKS: 12
     MBD_TESTS_PUBLIC_LOG_FILE: "mbdyn-tests-public-test-job.log"
     MBD_TESTS_PUBLIC_STATUS_FILE: "mbdyn-tests-public-test-job.status"
   stage: test    # It only starts when the job in the build stage completes successfully.
@@ -96,3 +98,55 @@ mbdyn-tests-public-test-job:   # This job runs in the test stage.
     paths:
       - $MBD_TESTS_PUBLIC_OUTPUT_DIR/$MBD_TESTS_PUBLIC_LOG_FILE
       - $MBD_TESTS_PUBLIC_OUTPUT_DIR/$MBD_TESTS_PUBLIC_STATUS_FILE
+
+mbdyn-tests-public-test-job-gcov:   # This job runs in the test stage.
+  variables:
+    MBD_TESTS_PUBLIC_LOG_FILE: "mbdyn-tests-public-test-job.log"
+    MBD_TESTS_PUBLIC_STATUS_FILE: "mbdyn-tests-public-test-job.status"
+  stage: test    # It only starts when the job in the build stage completes successfully.
+  needs:
+    - job: netcdf-c-build-job
+      artifacts: true
+    - job: netcdf-cxx4-build-job
+      artifacts: true
+    - job: mkl-build-job
+      artifacts: true
+    - job: mbdyn-build-job-gcov
+      artifacts: true
+  script:
+      - MBD_INSTALL_PREFIX=${CI_PROJECT_DIR}/${MBD_INSTALL_PREFIX_GCOV}
+      - OCT_PKG_INSTALL_PREFIX=${CI_PROJECT_DIR}/${OCT_PKG_INSTALL_PREFIX_GCOV}
+      - GMSH_INSTALL_PREFIX=${CI_PROJECT_DIR}/${GMSH_INSTALL_PREFIX}
+      - MBD_TESTS_PUBLIC_OUTPUT_DIR=${CI_PROJECT_DIR}/${MBD_TESTS_PUBLIC_OUTPUT_DIR_GCOV}
+      - MBD_TESTS_PUBLIC_INPUT_DIR=${CI_PROJECT_DIR}/${MBD_TESTS_PUBLIC_INPUT_DIR}
+      - echo "mbdyn-tests-public-test-job-gcov"
+      - export PATH=${MBD_INSTALL_PREFIX}/bin:${GMSH_INSTALL_PREFIX}/bin:${OCT_PKG_INSTALL_PREFIX}/bin:${PATH}
+      - export AWKPATH=${MBD_INSTALL_PREFIX}/share/awk:${AWKPATH}
+      - |
+        if ! test -d ${MBD_TESTS_PUBLIC_INPUT_DIR}; then
+          if ! git clone -b ${MBD_TESTS_PUBLIC_GITLAB_BRANCH} ${MBD_TESTS_PUBLIC_GITLAB} ${MBD_TESTS_PUBLIC_INPUT_DIR}; then
+            echo "Failed to clone ${MBD_TESTS_PUBLIC_GITLAB}"
+            exit 1
+          fi
+        fi
+      - test -d ${MBD_TESTS_PUBLIC_INPUT_DIR}
+      - cd ${MBD_TESTS_PUBLIC_INPUT_DIR}
+      - git pull --force
+      - cd ${CI_PROJECT_DIR}
+      - chmod +x testsuite/simple_testsuite.sh
+      - mkdir -p ${MBD_TESTS_PUBLIC_OUTPUT_DIR} ## needed for realpath
+      - log_file="${MBD_TESTS_PUBLIC_OUTPUT_DIR}/${MBD_TESTS_PUBLIC_LOG_FILE}"
+      - status_file="${MBD_TESTS_PUBLIC_OUTPUT_DIR}/${MBD_TESTS_PUBLIC_STATUS_FILE}"
+      - echo "unexpected" > "${status_file}"
+      - echo "-------------- PATCHED TESTS --------------------" | tee "${log_file}"
+      - test_status="failed"
+      - (/usr/bin/time --verbose testsuite/simple_testsuite_patched.sh --scale-when "always" --exit-status-mask "${MBD_TESTS_PUBLIC_EXIT_STATUS_MASK}" --timeout "${MBD_TESTS_PUBLIC_TIMEOUT}" --prefix-output "${MBD_TESTS_PUBLIC_OUTPUT_DIR}" --prefix-input "${MBD_TESTS_PUBLIC_INPUT_DIR}" --tasks "${MBD_TESTS_PUBLIC_NUM_TASKS}" ${MBD_SIMPLE_TESTSUITE_FLAGS} 2>&1 | tee -a "${log_file}") && test_status="passed"
+      - echo "${test_status}" > "${status_file}"
+  artifacts:
+    name: mbdyn-tests-public-test-job-gcov
+    expire_in: 24h
+    paths:
+      - $MBD_TESTS_PUBLIC_OUTPUT_DIR_GCOV/$MBD_TESTS_PUBLIC_LOG_FILE
+      - $MBD_TESTS_PUBLIC_OUTPUT_DIR_GCOV/$MBD_TESTS_PUBLIC_STATUS_FILE
+      - $MBD_BUILD_DIR_GCOV
+      
