Use tail -n1; cleanup old garbage

diff --git a/testsuite/octave-pkg-build-job.yml b/testsuite/octave-pkg-build-job.yml
--- a/testsuite/octave-pkg-build-job.yml
+++ b/testsuite/octave-pkg-build-job.yml
@@ -17,6 +17,7 @@ octave-pkg-build-job:       # This job runs in the build stage, which runs first
         - OCT_PKG_BUILD_DIR=${CI_PROJECT_DIR}/${OCT_PKG_BUILD_DIR}
         - OCT_PKG_INSTALL_PREFIX=${CI_PROJECT_DIR}/${OCT_PKG_INSTALL_PREFIX}
         - mkdir -p "${OCT_PKG_INSTALL_PREFIX}"
+        - rm -rf "${OCT_PKG_BUILD_DIR}" ## FIXME: Let's clean up old stuff only once, then remove this command!
         - mkdir -p "${OCT_PKG_BUILD_DIR}"
         - OCT_PKG_BINARY_DIR="${OCT_PKG_BUILD_DIR}/binary-packages"
         - mkdir -p "${OCT_PKG_BINARY_DIR}"
@@ -115,7 +116,7 @@ octave-pkg-build-job:       # This job runs in the build stage, which runs first
               case "${pkgname}" in
                   mboct-*-pkg)
                       if ! test -d "${pkgname}"; then
-                          if ! git clone -b "${pkg_branch}" "https://github.com/octave-user/${pkgname}.git" "${pkgname}"; then
+                          if ! git clone -b "${pkg_branch}" -- "https://github.com/octave-user/${pkgname}.git" "${pkgname}"; then
                               printf "failed to clone package \"%s\" from github.com\n" "${pkgname}"
                               exit 1
                           fi
@@ -142,11 +143,7 @@ octave-pkg-build-job:       # This job runs in the build stage, which runs first
                         exit 1
                       fi
 
-                      pkg_tar_files_binary=$(find "${OCT_PKG_BINARY_DIR}" -name "${pkgname}*.tar.gz")
-
-                      for pkg_tar_file_binary in ${pkg_tar_files_binary}; do
-                          echo "A binary package found: ${pkg_tar_file_binary}"
-                      done
+                      pkg_tar_file_binary=$(find "${OCT_PKG_BINARY_DIR}" -name "${pkgname}*.tar.gz" | tail -n1)
 
                       if ! test -f "${pkg_tar_file_binary}"; then
                           if ! make -C "${pkgname}" dist; then
@@ -154,6 +151,10 @@ octave-pkg-build-job:       # This job runs in the build stage, which runs first
                               exit 1
                           fi
 
+                          if ! test -d "${pkgname}"; then
+                              exit 1
+                          fi
+                          
                           pkg_tar_file=$(find "${pkgname}" '(' -type f -and -path "*/target/${pkgname}*.tar.gz" ')')
 
                           if ! test -f "${pkg_tar_file}"; then
@@ -172,11 +173,7 @@ octave-pkg-build-job:       # This job runs in the build stage, which runs first
                               exit 1
                           fi
 
-                          pkg_tar_files_binary=$(find "${OCT_PKG_BINARY_DIR}" -name "${pkgname}*.tar.gz")
-
-                          for pkg_tar_file_binary in ${pkg_tar_files_binary}; do
-                              echo "A binary package was found: ${pkg_tar_file_binary}"
-                          done
+                          pkg_tar_file_binary=$(find "${OCT_PKG_BINARY_DIR}" -name "${pkgname}*.tar.gz" | tail -n1)
 
                           if ! test -f "${pkg_tar_file_binary}"; then
                               printf "binary package \"%s\" not found\n" "${pkgname}"
